# Cloudflare Workers 部署模板
# 用于一键部署功能

[template]
name = "RSS_to_Telegram"
description = "基于 Cloudflare Workers 的 RSS Telegram 推送平台"
repository = "https://github.com/kvein10086/RSS_to_Telegram"
compatibility_date = "2024-01-01"

[template.vars]
# 环境变量（可选）
# TELEGRAM_BOT_TOKEN = ""
# TELEGRAM_CHAT_ID = ""

[template.kv_namespaces]
RSS_CONFIG = { binding = "RSS_CONFIG" }

[template.crons]
# 每30分钟检查一次 RSS 更新
rss_check = "*/30 * * * *"

[template.metadata]
author = "RSS Pusher Team"
version = "1.0.0"
tags = ["rss", "telegram", "automation", "news"]